version: 0.2
phases: null
install: null
runtime-versions: null
java: corretto8
build: null
commands:
  - echo Build started on `date`
  - mvn test
post_build:
  commands:
    - echo Build completed on `date`
    - mvn package
artifacts: null
files:
  - target/my-app-1.0-SNAPSHOT.jar
  - appspec.yml
discard-paths: 'yes'
